spring:
  config:
    activate:
      on-profile: dev
  application:
    name: commerce-gateway-development
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    baseline-version: 1
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true: true
      mail.smtp.ssl.trust: smtp.gmail.com
    from: ${MAIL_FROM}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope: public_profile, email
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v12.0/dialog/oauth
            token-uri: https://graph.facebook.com/v12.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

---

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"

---

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_SECRET_KEY}
  url:  ${VNPAY_PAY_URL}
  api-url: ${VNPAY_API_URL}
  return-url: ${VNPAY_RETURN_URL}
  ipn-url: ${VNPAY_IPN_URL}
jwt:
  timeout: ${JWT_TIME_OUT}
  secretKey: ${JWT_SECRET}
  expiryDay: ${REFRESH_TOKEN_EXPIRATION_DAYS}
  refreshKey: ${JWT_REFRESH_SECRET}
  resetKey: ${JWT_RESET_PASSWORD_SECRET}



## Database
#
#POSTGRES_DB=commercegatewaydb
#POSTGRES_USER=postgres
#POSTGRES_PASSWORD=12345
#
## Redis
#
#REDIS_HOST=redis
#REDIS_PORT=6379
#
## RabbitMQ
#
#RABBITMQ_HOST=rabbitmq
#RABBITMQ_PORT=5672
#RABBITMQ_USER=admin
#RABBITMQ_PASSWORD=admin123
#
## JWT & OTP
#
#JWT_SECRET=c92a0ed7d50b0146d9dd064ffffc49b1945c8d9d236841e837bb5e4ebc08f3a1
#JWT_REFRESH_SECRET=1e34c845918564fa8b0559a3d32182e2bee5e41a466e1e636f795eaa97c1ed7c
#JWT_RESET_PASSWORD_SECRET=7f3c1b0e8a4f26d9c7e9f2d11a50384b62c1e77d9452fae8cb38d40a19f06b52
#REFRESH_TOKEN_EXPIRATION_DAYS=7
#OTP_EXPIRATION_MIN=5
#JWT_TIME_OUT=10800000
#
## MailSender
#
#MAIL_HOST=smtp.gmail.com
#MAIL_PORT=587
#MAIL_USERNAME=qhuyddbmt123@gmail.com
#MAIL_PASSWORD=lbyjpyzajcrjkmjz
#MAIL_FROM=qhuyddbmt123@gmail.com
#
## VNPAY
#

#
## Google OAuth
#
#GOOGLE_CLIENT_ID=[602088036528-v5bdkkgbs4h4icr29bg453f5qbfpg9oi.apps.googleusercontent.com](http://602088036528-v5bdkkgbs4h4icr29bg453f5qbfpg9oi.apps.googleusercontent.com/)
#GOOGLE_CLIENT_SECRET=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yFm
#GOOGLE_REDIRECT_URI=http://localhost:8080/login/oauth2/code/google
#GOOGLE_FRONTEND_REDIRECT_URI=http://localhost:3000/oauth2/redirect/google